version: 2.1
executors:
  node14:
    docker:
      - image: circleci/node:14

commands:
  restore_cache_checkout:
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

  run_checkout:
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

  restore_cache_yarn:
    steps:
      - restore_cache:
          key: v1-yarn-{{ .Branch }}

  run_yarn:
    steps:
      - restore_cache_yarn
      - run:
          name: yarn install
          command: yarn install --no-progress --non-interactive --cache-folder ~/.cache/yarn
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-yarn-{{ .Branch }}

  install_chrome_headless_deps:
    steps:
      - run:
          command: sudo apt-get upgrade -y

      - run:
          name: Install Chrome headless dependencies
          working_directory: /
          command: |
            sudo apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
            libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
            libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
            libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
            ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget --fix-missing

  wait_for_app:
    steps:
      - run:
          shell: /bin/sh
          command: wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:3000/

jobs:
  # Checkout code and caches it
  setup:
    executor: node14
    working_directory: ~/upgrade-helper
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/upgrade-helper

  # Start app to run tests
  start:
    executor: node14
    working_directory: ~/upgrade-helper
    steps:
      - restore_cache_checkout
      - run_yarn
      - install_chrome_headless_deps
      - run:
          command: yarn start
          background: true
      - wait_for_app

  # Run lint and tests
  test:
    executor: node14
    working_directory: ~/upgrade-helper

    steps:
      - restore_cache_checkout
      - restore_cache_yarn
      - run: yarn run lint
      - run: yarn run test --runInBand

  # Deploy website to GitHub Pages
  deploy:
    executor: node14
    working_directory: ~/upgrade-helper
    steps:
      - restore_cache_checkout
      - run_yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy
          command: |
            if [[ $CIRCLE_PROJECT_USERNAME == "react-native-community" ]]; then
              git config --global user.email $GH_EMAIL
              git config --global user.name $GH_NAME

              yarn gh-pages -d build --message "[skip ci] Updates" --repo https://$GH_TOKEN@github.com/react-native-community/upgrade-helper.git
            else
              echo "Skipping deploy."
            fi

workflows:
  version: 2.1
  tests:
    jobs:
      - setup

      - start:
          requires:
            - setup

      - test:
          requires:
            - start
  deploy-to-gh-pages:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - master
              # Forked pull requests have `CIRCLE_BRANCH` set to pull/XXX
              ignore: /pull\/[0-9]+/

      - deploy:
          requires:
            - setup
