name: Lint & Test

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

  install:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Run lint
        run: yarn lint

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: yarn test --runInBand

  test-e2e:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Run e2e tests
        run: yarn test-e2e
