name: Lint & Test

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}
          path: ./**

  install:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Restore output
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.sha }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore yarn dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

  lint:
    needs: [setup, install]
    runs-on: ubuntu-latest
    steps:
      - name: Restore output
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.sha }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore yarn dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

  test:
    needs: [setup, install]
    runs-on: ubuntu-latest
    steps:
      - name: Restore output
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.sha }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore yarn dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test --runInBand

  test-e2e:
    needs: [setup, install]
    runs-on: ubuntu-latest
    steps:
      - name: Restore output
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.sha }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore yarn dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run e2e tests
        run: yarn test-e2e
